# Generated by Django 5.1.3 on 2024-12-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
